---@type RCLootCouncil
local addon = {}
loadfile(".specs/AddonLoader.lua")(nil, nil, addon).LoadArray {
	"Classes/Core.lua",
	[[Classes\Lib\RxLua\embeds.xml]],
}

describe("#RxLua", function()
	local Subject = addon.Require("rx.Subject")
	local Observable = addon.Require("rx.Observable")
	local Observer = addon.Require("rx.Observer")
	describe("#Subject", function()
		it("should handle basic Subject functions", function()

			local s = Subject.create()
			local o = Observable.fromSubject(s)
			local sp = spy.new()
			local ob = Observer.create(sp)
			local sub = o:take(1):subscribe(ob)
			assert.False(ob.stopped)
			assert.False(sub.unsubscribed)
			s(1)
			assert.True(ob.stopped)
			assert.True(sub.unsubscribed)
			s(2)
			s(3)

			assert.True(ob.stopped)
			sp:revert()
			ob = Observer.create(sp)
			local sub2 = o:subscribe(ob)
			s(1)
			s(2)
			assert.False(ob.stopped)
			assert.False(sub2.unsubscribed)
			sub2:unsubscribe()
			s(3)
			assert.False(ob.stopped)
			assert.True(sub2.unsubscribed)
		end)
	end)
	describe("#Observable", function()
		
		it("should handle basic Observable functions", function()
			local s = Subject.create()
			local o = Observable.create(function(observer)
				return s:subscribe(observer)
			end)
			local sp = spy.new()
			o:subscribe(sp)
			s("Test")
			assert.spy(sp).was_called(1)
			assert.spy(sp).was_called_with("Test")
		end)

		it("can create from Subjects", function()
			local s = Subject.create()
			local o = Observable.fromSubject(s)
			local sp = spy.new()
			o:subscribe(sp)
			s("Test")
			assert.spy(sp).was_called(1)
			assert.spy(sp).was_called_with("Test")
		end)
	end)
end)
